---
kind: ResourceQuota
apiVersion: v1
metadata:
  name: paulao5-quota
  namespace: paulao5
  labels:
    kubernetes.io/metadata.name: paulao5
    backstage.io/kubernetes-id: paulao5
    istio-injection: enabled
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi