---
kind: ResourceQuota
apiVersion: v1
metadata:
  name: test222-quota
  namespace: test222
  labels:
    kubernetes.io/metadata.name: test222
    backstage.io/kubernetes-id: test222
    istio-injection: enabled
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi