---
kind: ResourceQuota
apiVersion: v1
metadata:
  name: test1000-quota
  namespace: test1000
  labels:
    kubernetes.io/metadata.name: test1000
    backstage.io/kubernetes-id: test1000
    istio-injection: enabled
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi