---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test669
resources:
  - namespace.yaml
  - test669-quota.yaml
  - test669-deployment.yaml
  - test669-service.yaml
  - test669-vs.yaml
  - test669-hpa.yaml