---
kind: ResourceQuota
apiVersion: v1
metadata:
  name: test669-quota
  namespace: test669
  labels:
    kubernetes.io/metadata.name: test669
    backstage.io/kubernetes-id: test669
    istio-injection: enabled
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi