---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test667
resources:
  - namespace.yaml
  - test667-quota.yaml
  - test667-deployment.yaml
  - test667-service.yaml
  - test667-vs.yaml
  - test667-hpa.yaml