---
kind: ResourceQuota
apiVersion: v1
metadata:
  name: test777-quota
  namespace: test777
  labels:
    kubernetes.io/metadata.name: test777
    backstage.io/kubernetes-id: test777
    istio-injection: enabled
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi