---
kind: ResourceQuota
apiVersion: v1
metadata:
  name: test111-quota
  namespace: test111
  labels:
    kubernetes.io/metadata.name: test111
    backstage.io/kubernetes-id: test111
    istio-injection: enabled
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi