apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: test999-hpa
  namespace: test999
  labels:
    app: test999
    version: 0.0.1
    backstage.io/kubernetes-id: test999
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: test999
 minReplicas: 1
 maxReplicas: 4
 targetCPUUtilizationPercentage: 75