---
kind: ResourceQuota
apiVersion: v1
metadata:
  name: test999-quota
  namespace: test999
  labels:
    kubernetes.io/metadata.name: test999
    backstage.io/kubernetes-id: test999
    istio-injection: enabled
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi