---
kind: ResourceQuota
apiVersion: v1
metadata:
  name: test700-quota
  namespace: test700
  labels:
    kubernetes.io/metadata.name: test700
    backstage.io/kubernetes-id: test700
    istio-injection: enabled
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi