---
kind: ResourceQuota
apiVersion: v1
metadata:
  name: my-new-go-app-quota
  namespace: my-new-go-app
  labels:
    kubernetes.io/metadata.name: my-new-go-app
    backstage.io/kubernetes-id: my-new-go-app
    istio-injection: enabled
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi