apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: paulao5
  namespace: argocd
spec:
  project: default #every application belongs to a single project

  source:
    repoURL: https://github.com/paulofponciano-idp/gitops
    targetRevision: HEAD
    path: deployed_apps/paulao5/overlays
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
